name: fiona
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - numexpr
  - psutil
  - pip
  - c-compiler
  - cxx-compiler
  - cmake
  - make
  - gsl=2.8
  - fftw=3.3.*
  - libopenblas
  - llvm-openmp
